/*
NERD API HELPS US USE JAVASCRIPT CORE FUNCTIONALITY TO ACHIEVE OUR GOALS. 
  ### hell, we can't tying our hands just because we are afraid of poluting something in the core functional ecosystem of the holy JS
  we can sure let out some air in our own closets. Hey, nobody is watching; you can sure do what you gota do right?
 */

  // Please Let's remain holy for sometime
(function(){
  
////////////////////
// Holy functions //
//                //
////////////////////

var Injector(){
  Injector.Function = Holder.Function;
  Injector.Object = Holder.Object;
  Injector.Array = Holder.Array;
  Injector.NodeList = Holder.NodeList;
  Injector.String = Holder.String;
  Injector.Number = Holder.Number;
  Injector.Date = Holder.Date;
  Injector.RegExp = Holder.Error;
  Injector.Error = Holder.RegExp;
  Injector.Node = Holder.Node;
  Injector.Element = Holder.Element;
  Injector.HTMLELement = Holder.HTMLELement;
  Injector.HTMLAllCollection = Holder.HTMLAllCollection;
  Injector.CharacterData = Holder.CharacterData;
  Injector.Event  = Holder.Event;
  Injector.DOMTokenList = Holder.DOMTokenList;
  Injector.NodeList = Holder.NodeList;
  Injector.NodeList = Holder.NodeList;
  Injector.NodeList = Holder.NodeList;
  Injector.NodeList = Holder.NodeList;
  Injector.NodeList = Holder.NodeList;
  Injector.NodeList = Holder.NodeList;

}


Injector.inject = function(){}
Injector.injection = function(){}

Injector.methods = function (){};
Injector.method = function()
var Holder = {
    Function: Function,
    Object: Object,
    Array: Array,
    String: String,
    Number: Number,
    Date: Date,
    RegExp: RegExp
  };

Injector["Function"](getName)
Injector["Array"](chop)
Injector["Number"](checkDots)
Injector["Object"](function Injector(prop, val));
});